# Generated by Django 4.2.9 on 2024-01-05 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mosque', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mgallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mFile', models.FileField(upload_to='media', verbose_name='فایل')),
                ('mosqe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mosque.mmosque', verbose_name='مسجد')),
            ],
            options={
                'verbose_name': 'گالری',
                'verbose_name_plural': 'گالری ها',
            },
        ),
    ]
