# Generated by Django 4.2.9 on 2024-01-08 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registerEatekaf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mregistereatekaf',
            name='payment',
            field=models.CharField(blank=True, choices=[('خیر', 'خیر'), ('بله', 'بله')], max_length=50, null=True, verbose_name='وضعیت پرداخت'),
        ),
    ]
