# Generated by Django 4.2.9 on 2024-01-16 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registerEatekaf', '0004_alter_mregistereatekaf_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mregistereatekaf',
            name='payment',
            field=models.CharField(blank=True, choices=[('بله', 'بله'), ('خیر', 'خیر')], max_length=50, null=True, verbose_name='وضعیت پرداخت'),
        ),
    ]
