# Generated by Django 4.2.9 on 2024-01-08 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcontact',
            name='marital',
            field=models.CharField(choices=[('متاهل', 'متاهل'), ('مجرد', 'مجرد')], max_length=50, verbose_name='وضعیت تاهل'),
        ),
        migrations.AlterField(
            model_name='mcontact',
            name='testimonial',
            field=models.BooleanField(default=1, verbose_name='رضایت نامه'),
            preserve_default=False,
        ),
    ]
