# Generated by Django 4.2.9 on 2024-01-16 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_alter_mcontact_marital_alter_mcontact_testimonial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcontact',
            name='marital',
            field=models.CharField(choices=[('مجرد', 'مجرد'), ('متاهل', 'متاهل')], max_length=50, verbose_name='وضعیت تاهل'),
        ),
    ]
