# Generated by Django 4.2.9 on 2024-01-15 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mosque', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mmosque',
            name='link',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='لینک اتصال'),
        ),
    ]
