# Generated by Django 4.2.9 on 2024-01-16 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mosque', '0002_mmosque_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='mmosque',
            name='backup',
            field=models.CharField(default=1, max_length=200, verbose_name='اسم دارنده حساب'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mmosque',
            name='mastercard',
            field=models.CharField(default=1, max_length=16, verbose_name='شماره کارت'),
            preserve_default=False,
        ),
    ]
