# Generated by Django 4.2.9 on 2024-01-16 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contact', '0003_alter_mcontact_marital'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.BooleanField(verbose_name='عکاس')),
                ('editor', models.BooleanField(verbose_name='تدوین گر')),
                ('camera', models.BooleanField(verbose_name='فیلم بردار')),
                ('news', models.BooleanField(verbose_name='تولید خبر')),
                ('writer', models.BooleanField(verbose_name='نویسندگی')),
                ('adminis', models.BooleanField(verbose_name='مدیریت کانال مجازی')),
                ('poemer', models.BooleanField(verbose_name='شاعر')),
                ('madah', models.BooleanField(verbose_name='مداح و روضه خوانی')),
                ('adv', models.BooleanField(verbose_name='مبلغ')),
                ('backup', models.BooleanField(verbose_name='پشتیبانی')),
                ('engine', models.BooleanField(verbose_name='فنی و مهندسی')),
                ('teach', models.BooleanField(verbose_name='مدرس')),
                ('child', models.BooleanField(verbose_name='کودک و نوجوان')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.mcontact', verbose_name='فرد')),
            ],
            options={
                'verbose_name': 'توانایی',
                'verbose_name_plural': 'توانایی ها',
            },
        ),
    ]
