# Generated by Django 4.2.9 on 2024-01-16 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ability', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mability',
            name='adminis',
            field=models.BooleanField(blank=True, null=True, verbose_name='مدیریت کانال مجازی'),
        ),
        migrations.AlterField(
            model_name='mability',
            name='adv',
            field=models.BooleanField(blank=True, null=True, verbose_name='مبلغ'),
        ),
        migrations.AlterField(
            model_name='mability',
            name='backup',
            field=models.BooleanField(blank=True, null=True, verbose_name='پشتیبانی'),
        ),
        migrations.AlterField(
            model_name='mability',
            name='camera',
            field=models.BooleanField(blank=True, null=True, verbose_name='فیلم بردار'),
        ),
        migrations.AlterField(
            model_name='mability',
            name='child',
            field=models.BooleanField(blank=True, null=True, verbose_name='کودک و نوجوان'),
        ),
        migrations.AlterField(
            model_name='mability',
            name='editor',
            field=models.BooleanField(blank=True, null=True, verbose_name='تدوین گر'),
        ),
        migrations.AlterField(
            model_name='mability',
            name='engine',
            field=models.BooleanField(blank=True, null=True, verbose_name='فنی و مهندسی'),
        ),
        migrations.AlterField(
            model_name='mability',
            name='madah',
            field=models.BooleanField(blank=True, null=True, verbose_name='مداح و روضه خوانی'),
        ),
        migrations.AlterField(
            model_name='mability',
            name='news',
            field=models.BooleanField(blank=True, null=True, verbose_name='تولید خبر'),
        ),
        migrations.AlterField(
            model_name='mability',
            name='photo',
            field=models.BooleanField(blank=True, null=True, verbose_name='عکاس'),
        ),
        migrations.AlterField(
            model_name='mability',
            name='poemer',
            field=models.BooleanField(blank=True, null=True, verbose_name='شاعر'),
        ),
        migrations.AlterField(
            model_name='mability',
            name='teach',
            field=models.BooleanField(blank=True, null=True, verbose_name='مدرس'),
        ),
        migrations.AlterField(
            model_name='mability',
            name='writer',
            field=models.BooleanField(blank=True, null=True, verbose_name='نویسندگی'),
        ),
    ]
