# Generated by Django 4.2.9 on 2024-01-16 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ability', '0002_alter_mability_adminis_alter_mability_adv_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mability',
            name='adminis',
            field=models.BooleanField(default=1, verbose_name='مدیریت کانال مجازی'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mability',
            name='adv',
            field=models.BooleanField(default=1, verbose_name='مبلغ'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mability',
            name='backup',
            field=models.BooleanField(default=1, verbose_name='پشتیبانی'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mability',
            name='camera',
            field=models.BooleanField(default=1, verbose_name='فیلم بردار'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mability',
            name='child',
            field=models.BooleanField(default=1, verbose_name='کودک و نوجوان'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mability',
            name='editor',
            field=models.BooleanField(default=1, verbose_name='تدوین گر'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mability',
            name='engine',
            field=models.BooleanField(default=1, verbose_name='فنی و مهندسی'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mability',
            name='madah',
            field=models.BooleanField(default=1, verbose_name='مداح و روضه خوانی'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mability',
            name='news',
            field=models.BooleanField(default=1, verbose_name='تولید خبر'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mability',
            name='photo',
            field=models.BooleanField(default=1, verbose_name='عکاس'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mability',
            name='poemer',
            field=models.BooleanField(default=1, verbose_name='شاعر'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mability',
            name='teach',
            field=models.BooleanField(default=1, verbose_name='مدرس'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mability',
            name='writer',
            field=models.BooleanField(default=1, verbose_name='نویسندگی'),
            preserve_default=False,
        ),
    ]
