# Generated by Django 4.2.9 on 2024-01-16 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mosque', '0003_mmosque_backup_mmosque_mastercard'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='muser',
            name='mosque',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mosque.mmosque', verbose_name='نام مسجد'),
        ),
    ]
