# Generated by Django 4.2.9 on 2024-01-25 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MmosqueOpinion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peopleconvidienc', models.CharField(blank=True, choices=[('4', '4'), ('3', '3'), ('5', '5'), ('2', '2'), ('1', '1')], max_length=2, null=True, verbose_name='درصد راحتی مردم با سامانه')),
                ('mosqueconvidient', models.CharField(blank=True, choices=[('4', '4'), ('3', '3'), ('5', '5'), ('2', '2'), ('1', '1')], max_length=2, null=True, verbose_name='درصد راحتی کار شما با سامانه')),
                ('backupworker', models.CharField(blank=True, choices=[('4', '4'), ('3', '3'), ('5', '5'), ('2', '2'), ('1', '1')], max_length=2, null=True, verbose_name='تلاش پشتیبان سامانه در رفع امور مشکلات ')),
                ('averagconnect', models.CharField(blank=True, choices=[('4', '4'), ('3', '3'), ('5', '5'), ('2', '2'), ('1', '1')], max_length=2, null=True, verbose_name='به طور متوسط چند بار با پشتیبانی تماس گرفتید')),
                ('dataview', models.CharField(blank=True, choices=[('4', '4'), ('3', '3'), ('5', '5'), ('2', '2'), ('1', '1')], max_length=2, null=True, verbose_name='راحتی نمایش اطلاعات مسجد شما در بستر تبیان')),
                ('youropinion', models.CharField(blank=True, max_length=2, null=True, verbose_name='تا چه میزان سامانه تبیان را به دیگر مساجد معرفی می کنید')),
                ('yourexprienc', models.CharField(blank=True, choices=[('4', '4'), ('3', '3'), ('5', '5'), ('2', '2'), ('1', '1')], max_length=2, null=True, verbose_name='با استفاده از تجربه خود از سال های دیگر به سامانه امتیاز دهید')),
                ('backupaccess', models.CharField(blank=True, choices=[('4', '4'), ('3', '3'), ('5', '5'), ('2', '2'), ('1', '1')], max_length=2, null=True, verbose_name='در دسترس بودن پشتیبان')),
                ('backupsolver', models.CharField(blank=True, choices=[('4', '4'), ('3', '3'), ('5', '5'), ('2', '2'), ('1', '1')], max_length=2, null=True, verbose_name='رفع مشکلات سامانه توسط پشتیبان')),
                ('solver', models.CharField(blank=True, choices=[('4', '4'), ('3', '3'), ('5', '5'), ('2', '2'), ('1', '1')], max_length=2, null=True, verbose_name='تبیان تا چه حد مشکلات شما را برای ثبت نام اعتکاف حل کرده است')),
                ('mosquechoices', models.CharField(blank=True, choices=[('4', '4'), ('3', '3'), ('5', '5'), ('2', '2'), ('1', '1')], max_length=2, null=True, verbose_name='میزان آسانی فرآیند انتخاب مسجد در سایت')),
                ('paymethod', models.CharField(blank=True, choices=[('4', '4'), ('3', '3'), ('5', '5'), ('2', '2'), ('1', '1')], max_length=2, null=True, verbose_name='تا چه میزان روش پرداخت وجه اعتکاف به همین روش موجود در سایت مورد رضایت شماست')),
                ('description', models.TextField(blank=True, choices=[('4', '4'), ('3', '3'), ('5', '5'), ('2', '2'), ('1', '1')], null=True, verbose_name='هر چی مخی بوگو:')),
            ],
            options={
                'verbose_name': 'نظرسنجی مسجد',
                'verbose_name_plural': 'نظرسنجی مساجد',
            },
        ),
    ]
