# Generated by Django 4.2.9 on 2024-01-25 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mosqueopinion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mmosqueopinion',
            name='averagconnect',
            field=models.CharField(blank=True, choices=[('1', '1'), ('4', '4'), ('3', '3'), ('5', '5'), ('2', '2')], max_length=2, null=True, verbose_name='به طور متوسط چند بار با پشتیبانی تماس گرفتید'),
        ),
        migrations.AlterField(
            model_name='mmosqueopinion',
            name='backupaccess',
            field=models.CharField(blank=True, choices=[('1', '1'), ('4', '4'), ('3', '3'), ('5', '5'), ('2', '2')], max_length=2, null=True, verbose_name='در دسترس بودن پشتیبان'),
        ),
        migrations.AlterField(
            model_name='mmosqueopinion',
            name='backupsolver',
            field=models.CharField(blank=True, choices=[('1', '1'), ('4', '4'), ('3', '3'), ('5', '5'), ('2', '2')], max_length=2, null=True, verbose_name='رفع مشکلات سامانه توسط پشتیبان'),
        ),
        migrations.AlterField(
            model_name='mmosqueopinion',
            name='backupworker',
            field=models.CharField(blank=True, choices=[('1', '1'), ('4', '4'), ('3', '3'), ('5', '5'), ('2', '2')], max_length=2, null=True, verbose_name='تلاش پشتیبان سامانه در رفع امور مشکلات '),
        ),
        migrations.AlterField(
            model_name='mmosqueopinion',
            name='dataview',
            field=models.CharField(blank=True, choices=[('1', '1'), ('4', '4'), ('3', '3'), ('5', '5'), ('2', '2')], max_length=2, null=True, verbose_name='راحتی نمایش اطلاعات مسجد شما در بستر تبیان'),
        ),
        migrations.AlterField(
            model_name='mmosqueopinion',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='هر چی مخی بوگو:'),
        ),
        migrations.AlterField(
            model_name='mmosqueopinion',
            name='mosquechoices',
            field=models.CharField(blank=True, choices=[('1', '1'), ('4', '4'), ('3', '3'), ('5', '5'), ('2', '2')], max_length=2, null=True, verbose_name='میزان آسانی فرآیند انتخاب مسجد در سایت'),
        ),
        migrations.AlterField(
            model_name='mmosqueopinion',
            name='mosqueconvidient',
            field=models.CharField(blank=True, choices=[('1', '1'), ('4', '4'), ('3', '3'), ('5', '5'), ('2', '2')], max_length=2, null=True, verbose_name='درصد راحتی کار شما با سامانه'),
        ),
        migrations.AlterField(
            model_name='mmosqueopinion',
            name='paymethod',
            field=models.CharField(blank=True, choices=[('1', '1'), ('4', '4'), ('3', '3'), ('5', '5'), ('2', '2')], max_length=2, null=True, verbose_name='تا چه میزان روش پرداخت وجه اعتکاف به همین روش موجود در سایت مورد رضایت شماست'),
        ),
        migrations.AlterField(
            model_name='mmosqueopinion',
            name='peopleconvidienc',
            field=models.CharField(blank=True, choices=[('1', '1'), ('4', '4'), ('3', '3'), ('5', '5'), ('2', '2')], max_length=2, null=True, verbose_name='درصد راحتی مردم با سامانه'),
        ),
        migrations.AlterField(
            model_name='mmosqueopinion',
            name='solver',
            field=models.CharField(blank=True, choices=[('1', '1'), ('4', '4'), ('3', '3'), ('5', '5'), ('2', '2')], max_length=2, null=True, verbose_name='تبیان تا چه حد مشکلات شما را برای ثبت نام اعتکاف حل کرده است'),
        ),
        migrations.AlterField(
            model_name='mmosqueopinion',
            name='yourexprienc',
            field=models.CharField(blank=True, choices=[('1', '1'), ('4', '4'), ('3', '3'), ('5', '5'), ('2', '2')], max_length=2, null=True, verbose_name='با استفاده از تجربه خود از سال های دیگر به سامانه امتیاز دهید'),
        ),
        migrations.AlterField(
            model_name='mmosqueopinion',
            name='youropinion',
            field=models.CharField(blank=True, choices=[('1', '1'), ('4', '4'), ('3', '3'), ('5', '5'), ('2', '2')], max_length=2, null=True, verbose_name='تا چه میزان سامانه تبیان را به دیگر مساجد معرفی می کنید'),
        ),
    ]
